
export const SET_CURRENT = 'SET_CURRENT';
export const CLEAR_CURRENT = 'CLEAR_CURRENT';

export const CLEAR_FILTER = 'CLEAR_FILTER';

export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT = 'LOGOUT';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';
export const GET_ARTICLES = 'GET_ARTICLES';
export const ADD_ARTICLE = 'ADD_ARTICLE';
export const DELETE_ARTICLE = 'DELETE_ARTICLE';
export const UPDATE_ARTICLE = 'UPDATE_ARTICLE';
export const FILTER_ARTICLES = 'FILTER_ARTICLES';
export const CLEAR_ARTICLES = 'CLEAR_ARTICLES';
export const ARTICLE_ERROR = 'ARTICLE_ERROR';
export const GET_BUILDINGS = 'GET_BUILDINGS';
export const ADD_BUILDING = 'ADD_BUILDING';
export const DELETE_BUILDING = 'DELETE_BUILDINGS';
export const SET_CURRENT_BUILDING = 'SET_CURRENT_BUILDING';
export const CLEAR_CURRENT_BUILDING = 'CLEAR_CURRENT_BUILDING';
export const UPDATE_BUILDING = 'UPDATE_BUILDING';
export const CLEAR_FILTER_BUILDING = 'CLEAR_FILTER_BUILDING';
export const CLEAR_BUILDINGS = 'CLEAR_BUILDINGS';
export const FILTER_BUILDINGS = 'FILTER_BUILDINGS';
export const BUILDING_ERROR = 'BUILDING_ERROR';
